# Generated by Django 5.2 on 2025-05-06 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_created_date_comment_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 6, 7, 4, 17, 367105, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 6, 7, 4, 17, 366789, tzinfo=datetime.timezone.utc)),
        ),
    ]
